### ISSUE TITLE
Polotno Node error - svgElement.replaceColor(oldColor, newColor)#

### ISSUE THREAD

**Issue by vasanth-confetto** [polotno-project/polotno-board#12]
Hi Anton,
  Was trying this call serverside on NodeJS, and received an error that the method is not defined. 

svgElement.replaceColor(oldColor, newColor)#

**Comment by lavrton** [comment]
How do you use polotno from NodeJS? Do you use https://github.com/polotno-project/polotno-node? Or something different?

**Comment by vasanth-confetto** [comment]
HI Anton,
  I am using polotno-node, but it turns out I wasn't actually not using
replaceColor of polotno-node.  But i'm still facing issues with SVG color
replace on server side. Can you help me find out what's the issue below?


   - Attached is a JSON file. When loaded on Editor, the vertical accent
   line towards bottom left is white in color as it should be (because there's
   a colorsReplace value).
   - But when I try to save the same file using
   polotno-node's jsonToImageBase64 the SVG color is the original blue.


*What it looks like on the Editor :*
[image: image.png]

*Server-side generated Image :*

[image: Variant_0_19_d8a7b1.png]

**Comment by lavrton** [comment]
That is a bug in the polotno. I am going to work on it.

**Comment by lavrton** [comment]
Should be fixed with the last `polotno-node` release.
