### ISSUE TITLE
Preview panel within WorkspaceWrap

### ISSUE THREAD

**Issue by iamsterdam800** [polotno-project/polotno-board#20]
When building a design editor for a product with Polotno, the Preview panel is one of the main working tools.
Having the preview in a pop-up makes it harder to use while modifying the desing in the Workspace at the same time.
Besides, there's a lot of unused whitespace in the Workspace.

![image](https://user-images.githubusercontent.com/34508588/127746588-48735c92-f0cd-40f7-a519-a380f3d8d715.png)

We want to use Polotno to build something like instabox3d editor, with live 3D preview:

![image](https://user-images.githubusercontent.com/34508588/127746786-037cdeec-bd56-4c49-adb5-57463f150ac4.png)

So would be great to have the page design moved to the left, and on the right side to embed the preview.

**Comment by lavrton** [comment]
The layout made in this demo https://polotno.dev/docs/demo-book-cover-editor is just an example. 
You can make your own layout and place components very differently. 

Here is an example of side-by-side view: https://codesandbox.io/s/nice-payne-cr1xb?file=/src/index.js

**Comment by iamsterdam800** [comment]
Thanks for the example!
