### ISSUE TITLE
Change which object is initially selected on a page when editor loads

### ISSUE THREAD

**Issue by vanch3d** [polotno-project/polotno-board#24]
When the editor loads with a template or elements added to the active page, the last element in the list is selected by default. 
While not a problem in itself , it creates a bit of unexpected visual cues (border, handles, tools in top bar)

Notes:
- using version `0.29.0`
- creating store with a single page
- adding elements manually, e.g. `content.forEach((e) => store.activePage.addElement(e));`

**Comment by lavrton** [comment]
I was thinking that autoselect is the best default, because it most of the cases you want to have selected object, right after you added it.

If you don't want that behavior, you can select different objects.

```js
content.forEach((e) => store.activePage.addElement(e));
// deselect all
store.selectElements([]);
```
