### ISSUE TITLE
Ruler in the canvas

### ISSUE THREAD

**Issue by lavrton** [polotno-project/polotno-board#26]
We need to show rules on the edges of the page. 

And distances when we drag an element or hold a special hotkey.

Similar to how we have guidelines, but it tells you distance between elements and borders. Pro designers love this as it gives them accurate spacing and alignment.

**Comment by anthonylynch90** [comment]
https://user-images.githubusercontent.com/2746157/147350469-d04a41e8-9eaa-4446-bd70-e8ba92783b1b.mov

@lavrton Here is a video of how indesign works with ruler and margins. This will give a good picture as how it could be implemented. Obviously Indesign has the right hand side bar to show all the dimensions but this could be something where you display the height and width like a browser selector would show it
