### ISSUE TITLE
Keep image&svg urls in polotno json

### ISSUE THREAD

**Issue by iamsterdam800** [polotno-project/polotno-board#28]
I want to save the design on server in json format. Current json has all images (except the background) and svg's embedded in base64 as data urls. This makes it a very big file.
Is it possible to keep the original (unsplash) urls and have a flag on export e.g. toJSON(withOriginalUrls: true) to produce json with the original urls?

**Comment by lavrton** [comment]
The Unsplash images are saved as URL. Only SVG are embeds.

**Comment by lavrton** [comment]
Also by default, `polotno` is using base64 for uploaded images. But you can overwrite such behavior. 

The issue is not clear for me. Can you provide more info?

**Comment by iamsterdam800** [comment]
Indeed, the embedded images were not from unsplash, but the uploads. And I can save them seperately on the server.
Then there’s no issue!
Closing.
