### ISSUE TITLE
A "click-through" top-level element

### ISSUE THREAD

**Issue by iamsterdam800** [polotno-project/polotno-board#32]
My design template needs to have a top-level element (e.g. a frame with my logo), that I don't want the user to select or edit.

It should be fixed as a top-level element.
So when user adds elements to canvas, the frame should remain on top (covering user's elements).
It should not be possible to re-order elements (e.g. with Up, To forward) in a way that they appear on top of the frame.

The frame element should not respond to mouse events.
When the user clicks to select, their click should "go through" the frame element and select their element, not the frame.

So something like the "background" image, but on the fore side :)

**Comment by lavrton** [comment]
That is a good feature. I will schedule it for the next release.

**Comment by lavrton** [comment]
Released with `polotno@0.33.0`. `element.set({ selectable: false })`. or `store.setRole('admin')` to change this property from UI.

**Comment by iamsterdam800** [comment]
Hi Anton, thanks for super-quick implementation!
As far as I understood for my case, I'd need to set these two element attributes, correct?
```
          "selectable" : true,
          "alwaysOnTop" : true,
```
It's even better, that these two are seperately controlled!

**Comment by iamsterdam800** [comment]
`store.setRole('admin')` doesn't seem to have any effect.. I do not see any extra UI controls, when I add this line.
It's not that I need it actually.. just asking :)

**Comment by lavrton** [comment]
> As far as I understood for my case, I'd need to set these two element attributes, correct?

Yes.

> I do not see any extra UI controls

Right now, it is not very noticeable. Probably I will change it later.

<img width="926" alt="Screen Shot 2021-09-30 at 9 33 11" src="https://user-images.githubusercontent.com/1443320/135475612-5ef1f5cb-a7fa-4906-b9d1-043edce9755b.png">
