### ISSUE TITLE
hide elements in export

### ISSUE THREAD

**Issue by wshiwsbrding** [polotno-project/polotno-board#42]
"showInExport: false,"

seems to work with images but try as I may I cannot get a text type element to hide in an export.

for example,
this works to successfully hide the element in the export:
store.activePage.addElement({
  type: 'image',
  src: '/logo.png',
  keepRatio: false,
  x: 0,
  y: 0,
  width: 100,
  height: 100,
  selectable: false,
  showInExport: false,
});

however, this does not:
store.addPage();
store.activePage.addElement({
  type: 'text',
  text: 'Polotno tips',
  x: 50,
  y: 100,
  locked: true,  
  fontSize: 30,
  width: 200,
  align: 'center',
  fontFamily: 'Amatic SC',
  selectable: false,
  showInExport: false,
});

using 0.42.6 but tried some earlier versions with same result as well

**Comment by lavrton** [comment]
You are right. That is a bug. Just fixed it. Please watch for a new release somewhere in the future with the fix.

**Comment by wshiwsbrding** [comment]
Awesome!Sent from my phone
-------- Original message --------From: Anton Lavrenov ***@***.***> Date: 4/11/22  5:39 PM  (GMT-07:00) To: polotno-project/polotno-board ***@***.***> Cc: wshiwsbrding ***@***.***>, Author ***@***.***> Subject: Re: [polotno-project/polotno-board] hide elements in export (Issue #42) 
You are right. That is a bug. Just fixed it. Please watch for a new release somewhere in the future with the fix.

**Comment by lavrton** [comment]
New release is out!
