### ISSUE TITLE
After starting edit simple text it can't able to move or deselect either click outside or other elemenmt

### ISSUE THREAD

**Issue by JigarPrajpati** [polotno-project/polotno-board#50]
Added element
![image](https://user-images.githubusercontent.com/91531559/190855762-08034070-a607-4472-8ba4-6ee6af40e353.png)

started edit by double click
![image](https://user-images.githubusercontent.com/91531559/190855781-91989a7f-a836-487d-ac60-e630d07a2550.png)

clicked outside in order to start moving the text element
![image](https://user-images.githubusercontent.com/91531559/190855799-b6024b0a-a6f5-4c08-8da2-69385414eb34.png)

but i can't able and it keep remain in edit mode

**Comment by lavrton** [comment]
Interesting. I never saw this. In what browser do you have it?

**Comment by lavrton** [comment]
Should be fixed with the last `polotno` version.
