### ISSUE TITLE
How to write upload iamge server code in pure javascript?

### ISSUE THREAD

**Issue by JigarPrajpati** [polotno-project/polotno-board#51]
i using pure javascript for pootno, with pure javascript only, so how can i write this function in pure javascript?

![image](https://user-images.githubusercontent.com/91531559/190856410-a22ac9e8-6523-48a9-8fb4-33e7062b8477.png)

**Comment by lavrton** [comment]
I don't understand your question. Isn't it pure javascript already?

**Comment by JigarPrajpati** [comment]
You're right sir, but it's related to react like import and all, in pure simple javascript/jquery it's not supporting import and all so how can i do it in simple javacript/jquery?

**Comment by lavrton** [comment]
For now there is no API for that. Only via import env.
