### ISSUE TITLE
How to display elements off page?

### ISSUE THREAD

**Issue by djrobby** [polotno-project/polotno-board#53]
As per title. See attached image for reference. I would like to see the "Sun" element outside of the page as well. Thanks in advance.

![SS_20220927_7](https://user-images.githubusercontent.com/22199/192540549-58bc2a8e-e5eb-4686-9d97-59fa09fe447e.jpg)

**Comment by lavrton** [comment]
Why do you need to see it there?

**Comment by djrobby** [comment]
For our specific application, it's handy to have these page related elements readily accessible near the page(s) to be able to drag/drop and test variations (see ex#1 below). Also, once you drag an element off the page, it still remains in the layers and you have no easy way of identifying it unless it's selected (see ex#2 below).

ex#1:
![SS_20220927_8](https://user-images.githubusercontent.com/22199/192554672-81420cea-3ddf-4dc7-9d77-be0d134291ec.jpg)

ex#2:
![SS_20220927_9](https://user-images.githubusercontent.com/22199/192554698-2602974c-e053-4230-b163-10840cedd2cb.jpg)

**Comment by djrobby** [comment]
Thank you 🙏

**Comment by lavrton** [comment]
👍
