### ISSUE TITLE
Adopt Polotno UI for mobile

### ISSUE THREAD

**Issue by lavrton** [polotno-project/polotno-board#6]
I am not sure yet who/how will use polotno on mobile.

**Comment by vasanth-confetto** [comment]
We'll definitely be interested in this. From our own user research, lots of users create designs on Mobile using Canva. So we'll be super keen to upvote this.

**Comment by lavrton** [comment]
I just released `0.25.5` with experimental mobile support. https://polotno.dev/changelog/

There are still a lot of issues we will need to resolve. It is a first iteration.
