### ISSUE TITLE
Add SVG saving option to the app

### ISSUE THREAD

**Issue by BhavayBSingla** [polotno-project/polotno-board#61]

**Comment by lavrton** [comment]
@BhavayBSingla can you share your use case? Why do you need svg?

**Comment by brycelund** [comment]
We would love vector export support either in SVG or PDF format. We're using Polotno to create large graphics (4 by 8 feet) and having a vector graphics export option would make our file sizes much smaller.

**Comment by lavrton** [comment]
Polotno already has support for it. May require some polishing on some cases.
