### ISSUE TITLE
Ability to select overlapping or underlying elements, such as PNG images and text, regardless of their positions.

### ISSUE THREAD

**Issue by Craetivo** [polotno-project/polotno-board#72]
Please review the brief clip comparing Polotno with another platform for a clearer understanding.

https://github.com/polotno-project/polotno-board/assets/165745090/ccb582da-de33-4c3d-a2f3-6ced40697113

**Comment by lavrton** [comment]
For now, I am marking this as "wont fix", until we have some other related requests.
It is by design to have whole bounding box as clickable area.
