### ISSUE TITLE
Remove background from images

### ISSUE THREAD

**Issue by lavrton** [polotno-project/polotno-board#8]
There are many hot services that are using ML to remove background for the images. It will be cool to have that feature in the polotno.

We can use some API for that. But they are all expensive, so I can not provide them for free. Can we have a client-side solution for that?

**Comment by fatehwaharp** [comment]
Maybe as for now you can integrate it with official adobe api, its currently free right now, while in beta.

https://www.adobe.io/apis/creativecloud/photo-imaging-api/api-demo.html?ref=imagecutout

**Comment by lavrton** [comment]
Just released initial integration.
