### ISSUE TITLE
Open the pages timeline and add pages: it makes network calls to GET /null which fails with 404 not found

### ISSUE THREAD

**Issue by ADTC** [polotno-project/polotno-board#82]
You can easily reproduce it in [Polotno Studio](https://studio.polotno.dev/), and even in a very basic Polotno app. Simply open the pages timeline and add pages, then observe Dev Tools:

<img width="460" alt="image" src="https://github.com/user-attachments/assets/9de331f7-9c18-4acb-97ce-fbce77dd29bb">

For the sake of searching, noting here different variations:

```
GET https://studio.polotno.dev/null 404 (Not Found)
GET http://localhost:3000/null 404 (Not Found)
GET http://localhost:3001/null 404 (Not Found)
GET http://localhost:3002/null 404 (Not Found)
GET http://localhost:3003/null 404 (Not Found)
GET http://localhost:3004/null 404 (Not Found)
```
Also, in `npm run dev`/`next dev` logs:
```
GET /null 404 in 245ms (etc.)
```

This was extremely difficult to track down BTW. I had to create a fresh project, and slowly bring in code from broken project bit by bit until I found the culprit line:

```tsx
<PagesTimeline store={store} defaultOpened />
```

Then I re-did the test by adding just this bit into a fresh basic Polotno app. It was also reproducible.

That's when I figured out, I could also test this in the Studio website simply by opening the pages timeline and adding pages.

**Comment by lavrton** [comment]
Thanks for the report. I made a fix. Will release very soon.

**Comment by ADTC** [comment]
Thank you. What will be the version number?

**Comment by lavrton** [comment]
You can try the last one. https://polotno.com/changelog
